 <ul>
 	<link rel="stylesheet" href="estilo.css" type="text/css">
 		<div id=menumenu>
 		Navegação
		<li><a href="#" class="selected">Home</a></li>
		<li><a href="#" class="selected">Sementes de Frutas</a></li>
		<li><a href="#" class="selected">Sementes de Verduras</a></li>
		<li><a href="#" class="selected">Sementes de Flores</a></li>
		<li><a href="#" class="selected">Sementes Diversas</a></li>
		<li><a href="#" class="selected">Como  Comprar</a></li>
	</div>
</ul>